# Start the imports

import os
import wx
import wx.lib.scrolledpanel as scrolled

from Widgets import BaseListCtrl, MultiComboBox
from Constants import _toolTips

if wx.Platform != "__WXMAC__":
    from Widgets import TransientPopup


class BaseBuilderPanel(scrolled.ScrolledPanel):

    def __init__(self, parent, projectName, creationDate, name):
        """
        Default class constructor.

        @param projectName: the name of the project we are working on
        @param creationDate: the date and time the project was created

        """
        
        scrolled.ScrolledPanel.__init__(self, parent, name=name)
        self.MainFrame = wx.GetTopLevelParent(self)

        # I need this flag otherwise all the widgets start sending changed
        # events when I first populate the full panel
        
        self.created = False
        self.tipWindow = None
        

    # ========================== #
    # Methods called in __init__ #
    # ========================== #


    def BindEvents(self):
        """ Binds the event for almost all the widgets in PyInstallerPanel (except list controls). """

        isMac = wx.Platform == "__WXMAC__"

        for child in self.GetChildren():
            if isinstance(child, wx.TextCtrl):
                # That's a text control
                self.Bind(wx.EVT_TEXT, self.OnUserChange, child)
            elif isinstance(child, wx.combo.OwnerDrawnComboBox):
                # that's a combobox
                self.Bind(wx.EVT_COMBOBOX, self.OnUserChange, child)
            elif isinstance(child, wx.CheckBox):
                # That's a checkbox
                self.Bind(wx.EVT_CHECKBOX, self.OnUserChange, child)
            elif isinstance(child, wx.FilePickerCtrl):
                # and a file picker
                self.Bind(wx.EVT_FILEPICKER_CHANGED, self.OnUserChange, child)
            elif isinstance(child, wx.RadioButton):
                self.Bind(wx.EVT_RADIOBUTTON, self.OnUserChange, child)
                
            if isMac:
                child.SetWindowVariant(wx.WINDOW_VARIANT_SMALL)
        

    def BindToolTips(self):

        for child in self.GetChildren():
            if isinstance(child, wx.TextCtrl) or isinstance(child, wx.combo.OwnerDrawnComboBox) \
               or isinstance(child, wx.CheckBox) or isinstance(child, wx.FilePickerCtrl) \
               or isinstance(child, wx.RadioButton) or isinstance(child, wx.ListCtrl):
                child.Bind(wx.EVT_ENTER_WINDOW, self.OnEnterWindow)
                child.Bind(wx.EVT_LEAVE_WINDOW, self.OnLeaveWindow)
                
        
    # ============== #
    # Event handlers #
    # ============== #
    
    def OnChildFocus(self, event):
        """ Overridden method, to stop scrolledpanel from moving scrollbars. """

        pass


    def OnEnterWindow(self, event):

        if not self.MainFrame.showTips:
            return
        
        if self.tipWindow:
            return

        obj = event.GetEventObject()
        compiler = self.GetName()
        option = obj.GetName()

        if compiler not in _toolTips:
            return

        if option not in _toolTips[compiler]:
            return     

        options = _toolTips[compiler]
        tip = options[option]

        tip = tip.split("<note>")
        if len(tip) > 1:
            tip, note = tip
        else:
            tip, note = tip[0], None

        self.tipWindow = TransientPopup(self, compiler, option, tip, note)
        

    def OnLeaveWindow(self, event):

        if not self.tipWindow:
            return

        self.tipWindow.Destroy()
        self.tipWindow = None
        

    def OnUserChange(self, event):
        """ Handles all the events generated by the widgets (except list controls). """

        if not self.created:
            # No data yet, wait to be populated before whining
            return

        # Get the object that generated the event
        window = event.GetEventObject()
        # And retrieve its name
        windowName = window.GetName()

        # Get the value from the widget
        value = self.GetWindowValues(windowName, window)
        if isinstance(window, wx.CheckBox):
            # If it came from the xp manifest checkbox, update the
            # associated list control
            self.UpdateResourceList(windowName, value)

        # If it came from the zipfile or the dist checkbox, enable or
        # disable their associated text controls
        self.EnableAssociatedText(windowName, value)
        # Give visual feedback to the user that the model has changed
        if windowName in ["onedir", "onefile"]:
            # Hack for PyInstaller options
            otherName = (windowName == "onedir" and ["onefile"] or ["onedir"])[0]
            self.GiveScreenFeedback(otherName, not value)

        self.GiveScreenFeedback(windowName, value)
        
        event.Skip()


    # ================= #
    # Auxiliary methods #
    # ================= #
    
    def GetWindowValues(self, windowName, window=None):
        """ Retrieve the current value(s) displayed in a widget. """

        if window is None:
            # No window, find it by name
            window = self.FindWindowByName(windowName)
            
        if isinstance(window, wx.FilePickerCtrl):
            # It's a file path
            value = window.GetPath()
        elif isinstance(window, wx.ListCtrl):
            # It's a bit more complicated... translate it to something that
            # the project can actually understand
            value = window.TranslateToProject(window)
        else:
            if not isinstance(window, wx.lib.buttons.ThemedGenBitmapTextButton):
                # It's a text control or a checkbox
                value = window.GetValue()

        return value

    
    def GiveScreenFeedback(self, windowName, value, changeIcon=True):
        """ Gives visual feedback to the user that the model has changed. """

        # Retrieve the project stored in the parent (LabelBook) properties
        project = self.GetParent().GetProject()
        # Update the project, without saving it to the database
        project.Update(self.GetName(), windowName, value)

        if changeIcon:
            # Update the icon and the project name on the wx.aui.AuiNotebook tab
            self.MainFrame.UpdatePageBitmap(project.GetName() + "*", 1)


    def UpdateResourceList(self, windowName, value):
        """
        Updates the "other_resources" list when the user checks/unchecks the
        xp manifest checkbox.
        """

        if windowName != "manifest_file":
            # No, it wasn't him...
            return

        if value == 1:
            # Check if the "other_resources" list has a manifest item
            if self.otherResourceList.HasManifest():
                # Yes, it has, go back
                return
            # Add the manifest item to the "other_resources" list
            self.otherResourceList.AddManifest()
        else:
            # Unchecked, remove the manifest item
            self.otherResourceList.DeleteManifest()

        # Translate the change made to something understandable by the project
        values = self.otherResourceList.TranslateToProject()
        # Give visual feedback to the user that the model has changed
        self.GiveScreenFeedback(self.otherResourceList.GetName(), values)


    def UpdateLabel(self, projectName, creationDate):
        """ Updates the project name and creation date when the user rename a project. """
                
        self.label.SetLabel("%s options for: %s (Created: %s)"%(self.GetName(), projectName, creationDate))
        self.label.Refresh()


    def SetConfiguration(self, configuration, delete=False):
        """ Populates all the widgets with the values coming from the project. """

        onedir = ("onedir" in configuration and [configuration["onedir"]] or [None])[0]
        onefile = ("onefile" in configuration and [configuration["onefile"]] or [None])[0]

        # Loop over all the keys, values in the dictionary
        for key, value in configuration.items():
            if isinstance(value, list):
                if value:
                    if key == "options":
                        # It's one of the obscure check boxes options
                        continue
                    else:
                        # It's surely a list control, call its method
                        lst = self.FindWindowByName(key)
                        if delete:
                            lst.DeleteAllItems()

                        lst.PopulateList(value)
            else:
                # Hack for PyInstaller
                if key == "onedir":
                    if onefile:
                        continue
                elif key in ["plistCode", "plist_code"]:
                    # Mac py2app things, used later
                    continue
                
                # It's something we can easily handle here
                self.SetProjectOptions(key, value)

        # Just re-affirm that we are created and ready to receive events
        self.created = True
        

    def SetProjectOptions(self, key, value):
        """ Populates all the widgets (except list controls). """

        # Find the window given its name (that is a key in the project dictionary)        
        window = self.FindWindowByName(key)
        if isinstance(window, wx.TextCtrl) or isinstance(window, wx.combo.OwnerDrawnComboBox):
            # That's easy
            window.SetValue(str(value))
        elif isinstance(window, wx.RadioButton):
            # Radiobuttons are not very user friendly...
            window.SetValue(bool(value))
        elif isinstance(window, wx.CheckBox):
            # comboboxes needs integer values
            window.SetValue(int(value))
            # If it came from the zipfile or the dist checkbox, enable or
            # disable their associated text controls
            self.EnableAssociatedText(key, value)
        else:
            # It's a file picker control
            window.SetPath(value)
                

    def EnableAssociatedText(self, windowName, value):
        """
        Enables/disables the text controls associated with the zipfile checkbox
        or the dist checkbox.
        """

        if windowName.find("_choice") < 0:
            # No, it wasn't him
            return

        # Check if a text control with this name can exist...        
        possibleTextName = windowName.replace("_choice", "")
        possibleTextCtrl = self.FindWindowByName(possibleTextName)
        if possibleTextCtrl:
            # Found it: enable or disable it accordingly
            possibleTextCtrl.Enable(int(value))


